// latest is an explicit flag — when WordPress is connected, this comes from a WP tag/category
export const posts = [
  {
    id: 1,
    slug: "rigveda-poetry-of-dawn",
    title: "Rigveda and the Poetry of Dawn",
    excerpt: "A gentle reading of Vedic hymns that celebrate light, rhythm, and the sacred symbolism of morning.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    readTime: "6 min read", author: "Anaya Sharma", date: "12 Mar 2026",
    featured: true, trending: true, latest: false,
    categorySlug: "vedas", categoryName: "Vedas",
    subcategorySlug: "rigveda", subcategoryName: "Rigveda",
  },
  {
    id: 2,
    slug: "sacred-action-yajurveda",
    title: "Sacred Action in the Yajurveda",
    excerpt: "Understanding how ritual language shaped intention, discipline, and the culture of offering.",
    image: "https://images.unsplash.com/photo-1518562180175-34a163b1a9a6?auto=format&fit=crop&w=1200&q=80",
    readTime: "5 min read", author: "Dev Mehta", date: "18 Mar 2026",
    featured: false, trending: true, latest: true,
    categorySlug: "vedas", categoryName: "Vedas",
    subcategorySlug: "yajurveda", subcategoryName: "Yajurveda",
  },
  {
    id: 3,
    slug: "samveda-veda-of-melody",
    title: "Why the Samveda Is Called the Veda of Melody",
    excerpt: "A content-focused introduction to chant, sound, and the role of recitation in spiritual memory.",
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80",
    readTime: "4 min read", author: "Rhea Kulkarni", date: "22 Mar 2026",
    featured: true, trending: false, latest: true,
    categorySlug: "vedas", categoryName: "Vedas",
    subcategorySlug: "samveda", subcategoryName: "Samveda",
  },
  {
    id: 4,
    slug: "healing-wisdom-atharvaveda",
    title: "Healing and Household Wisdom in the Atharvaveda",
    excerpt: "Exploring the practical, symbolic, and protective dimensions of one of the most distinctive Vedas.",
    image: "https://images.unsplash.com/photo-1519834785169-98be25ec3f84?auto=format&fit=crop&w=1200&q=80",
    readTime: "7 min read", author: "Kavya Rao", date: "27 Mar 2026",
    featured: false, trending: true, latest: true,
    categorySlug: "vedas", categoryName: "Vedas",
    subcategorySlug: "atharvaveda", subcategoryName: "Atharvaveda",
  },
  {
    id: 5,
    slug: "isha-upanishad-art-of-enough",
    title: "Isha Upanishad and the Art of Enough",
    excerpt: "A modern reflection on fullness, stewardship, and living with grace in a restless age.",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1200&q=80",
    readTime: "5 min read", author: "Mira Sen", date: "03 Apr 2026",
    featured: true, trending: false, latest: true,
    categorySlug: "upanishads", categoryName: "Upanishads",
    subcategorySlug: "isha-upanishad", subcategoryName: "Isha Upanishad",
  },
  {
    id: 6,
    slug: "kena-upanishad-who-moves-the-mind",
    title: "Kena Upanishad: Who Moves the Mind?",
    excerpt: "A crisp guide to one of the most compelling philosophical questions in the Upanishadic tradition.",
    image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1200&q=80",
    readTime: "6 min read", author: "Arjun Bedi", date: "08 Apr 2026",
    featured: false, trending: true, latest: false,
    categorySlug: "upanishads", categoryName: "Upanishads",
    subcategorySlug: "kena-upanishad", subcategoryName: "Kena Upanishad",
  },
  {
    id: 7,
    slug: "katha-upanishad-fearlessness",
    title: "Lessons on Fearlessness from the Katha Upanishad",
    excerpt: "A thoughtful reading of Nachiketa's dialogue and its continued relevance for seekers today.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80",
    readTime: "7 min read", author: "Saanvi Iyer", date: "12 Apr 2026",
    featured: true, trending: true, latest: false,
    categorySlug: "upanishads", categoryName: "Upanishads",
    subcategorySlug: "katha-upanishad", subcategoryName: "Katha Upanishad",
  },
  {
    id: 8,
    slug: "mundaka-upanishad-higher-knowledge",
    title: "Higher Knowledge in the Mundaka Upanishad",
    excerpt: "How ancient teachers distinguished information from wisdom, and why that still matters.",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
    readTime: "4 min read", author: "Ishita Nair", date: "16 Apr 2026",
    featured: false, trending: false, latest: true,
    categorySlug: "upanishads", categoryName: "Upanishads",
    subcategorySlug: "mundaka-upanishad", subcategoryName: "Mundaka Upanishad",
  },
  {
    id: 9,
    slug: "dinacharya-grounded-morning",
    title: "Dinacharya for a Grounded Morning",
    excerpt: "Simple Ayurvedic routines for waking gently, supporting digestion, and beginning the day with clarity.",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80",
    readTime: "5 min read", author: "Nisha Kapoor", date: "20 Apr 2026",
    featured: true, trending: true, latest: true,
    categorySlug: "ayurveda", categoryName: "Ayurveda",
    subcategorySlug: "dinacharya", subcategoryName: "Dinacharya",
  },
  {
    id: 10,
    slug: "aahara-eating-with-awareness",
    title: "Aahara: Eating with Season and Awareness",
    excerpt: "A clean, practical introduction to Ayurvedic food principles without making wellness feel complicated.",
    image: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80",
    readTime: "6 min read", author: "Ritu Malhotra", date: "24 Apr 2026",
    featured: false, trending: true, latest: false,
    categorySlug: "ayurveda", categoryName: "Ayurveda",
    subcategorySlug: "aahara", subcategoryName: "Aahara",
  },
  {
    id: 11,
    slug: "ritucharya-seasonal-adjustment",
    title: "Ritucharya and the Beauty of Seasonal Adjustment",
    excerpt: "Why small changes in food, sleep, and movement can restore balance across changing climates.",
    image: "https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1200&q=80",
    readTime: "5 min read", author: "Tanvi Arora", date: "28 Apr 2026",
    featured: true, trending: false, latest: true,
    categorySlug: "ayurveda", categoryName: "Ayurveda",
    subcategorySlug: "ritucharya", subcategoryName: "Ritucharya",
  },
  {
    id: 12,
    slug: "dravyaguna-everyday-herbs",
    title: "Understanding Dravyaguna Through Everyday Herbs",
    excerpt: "A beginner-friendly editorial piece on qualities, taste, potency, and practical herbal awareness.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    readTime: "7 min read", author: "Leher Joshi", date: "02 May 2026",
    featured: false, trending: true, latest: true,
    categorySlug: "ayurveda", categoryName: "Ayurveda",
    subcategorySlug: "dravyaguna", subcategoryName: "Dravyaguna",
  },
  {
    id: 13,
    slug: "asana-steady-ease",
    title: "Asana as a Practice of Steady Ease",
    excerpt: "Moving beyond performance to rediscover posture as a space of awareness, alignment, and calm.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80",
    readTime: "5 min read", author: "Aditi Jain", date: "06 May 2026",
    featured: true, trending: true, latest: false,
    categorySlug: "yoga", categoryName: "Yoga",
    subcategorySlug: "asana", subcategoryName: "Asana",
  },
  {
    id: 14,
    slug: "pranayama-focused-energy",
    title: "Pranayama for Focused Energy",
    excerpt: "A modern overview of breath regulation, nervous system balance, and daily mental clarity.",
    image: "https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=1200&q=80",
    readTime: "4 min read", author: "Vihan Sethi", date: "09 May 2026",
    featured: false, trending: true, latest: true,
    categorySlug: "yoga", categoryName: "Yoga",
    subcategorySlug: "pranayama", subcategoryName: "Pranayama",
  },
  {
    id: 15,
    slug: "meditation-discipline-of-returning",
    title: "Meditation and the Discipline of Returning",
    excerpt: "A readable guide to stillness as a repeated act of attention rather than a perfect state.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80",
    readTime: "6 min read", author: "Pooja Deshpande", date: "12 May 2026",
    featured: true, trending: false, latest: true,
    categorySlug: "yoga", categoryName: "Yoga",
    subcategorySlug: "meditation", subcategoryName: "Meditation",
  },
  {
    id: 16,
    slug: "yoga-sutras-modern-eyes",
    title: "Reading the Yoga Sutras with Modern Eyes",
    excerpt: "A premium editorial introduction to discipline, mind, and liberation for thoughtful contemporary readers.",
    image: "https://images.unsplash.com/photo-1528715471579-d1bcf0ba5e83?auto=format&fit=crop&w=1200&q=80",
    readTime: "7 min read", author: "Rahul Trivedi", date: "15 May 2026",
    featured: false, trending: true, latest: true,
    categorySlug: "yoga", categoryName: "Yoga",
    subcategorySlug: "yoga-sutras", subcategoryName: "Yoga Sutras",
  },
];
